// cityData.js
const cityData = {    
	"Afghanistan": ["Kabul", "Herat", "Mazar-i-Sharif", "Kandahar", "Jalalabad", "Kunduz", "Baghlan", "Ghazni", "Bamyan", "Nangarhar"],
	"Andorra": ["Andorra la Vella", "Escaldes-Engordany", "Encamp", "Sant Julià de Lòria", "Escaldes", "La Massana", "Ordino", "Canillo"],
	"Albania": ["Tirana", "Durrës", "Vlorë", "Shkodër", "Fier", "Elbasan", "Korçë", "Shijak", "Lushnjë", "Sarandë"],
	"Algeria": ["Algiers", "Oran", "Constantine", "Annaba", "Blida", "Biskra", "Batna", "Sétif", "Chlef", "Tiaret"],
    "Angola": ["Luanda", "N'dalatando", "Huambo", "Lobito", "Kuito", "Benguela", "Malanje", "Cabinda", "Uige", "Caxito"],
    "Antigua and Barbuda": ["St. John's", "All Saints", "Liberta", "Osbourn", "Falmouth", "Willikies", "Bolands", "Parham", "John Hughes", "Yorks Village"],
    "Argentina": ["Buenos Aires", "Córdoba", "Rosario", "Mendoza", "La Plata", "San Miguel de Tucumán", "Mar del Plata", "Salta", "Santa Fe", "Corrientes"],
    "Armenia": ["Yerevan", "Gyumri", "Vanadzor", "Vagharshapat", "Vardenis", "Kapan", "Kirovakan", "Abovyan", "Sevan", "Artik"],
    "Australia": ["Sydney", "Melbourne", "Brisbane", "Perth", "Adelaide", "Gold Coast", "Canberra", "Hobart", "Darwin", "Newcastle"],
    "Austria": ["Vienna", "Salzburg", "Graz", "Innsbruck", "Linz", "Klagenfurt", "Villach", "Wels", "Steyr", "Dornbirn"],
    "Azerbaijan": ["Baku", "Ganja", "Mingachevir", "Sumqayit", "Lankaran", "Mingachevir", "Yevlakh", "Sheki", "Zagatala", "Guba"],
    "Bahamas": ["Nassau", "Freeport", "West End", "Cooper's Town", "Marsh Harbour", "Abaco", "Bimini", "Harbour Island", "Exuma", "Long Island"],
    "Bahrain": ["Manama", "Riffa", "Muharraq", "A'ali", "Isa Town", "Sitra", "Jidhafs", "Hamad Town", "Sanad", "Malkiya"],
    "Bangladesh": ["Dhaka", "Chittagong", "Khulna", "Rajshahi", "Sylhet", "Barisal", "Rangpur", "Mymensingh", "Narayanganj", "Comilla"],
    "Barbados": ["Bridgetown", "Speightstown", "Oistins", "Holetown", "Saint Lawrence", "St. George", "Christ Church", "St. Michael", "St. John", "St. Peter"],
    "Belarus": ["Minsk", "Gomel", "Mogilev", "Vitebsk", "Grodno", "Brest", "Baranovichi", "Bobruisk", "Polotsk", "Pinsk"],
    "Belgium": ["Brussels", "Antwerp", "Ghent", "Charleroi", "Liège", "Bruges", "Namur", "Leuven", "Mons", "Aalst"],
    "Belize": ["Belmopan", "Belize City", "San Ignacio", "Orange Walk Town", "Corozal Town", "Dangriga", "Punta Gorda", "San Pedro", "Benque Viejo del Carmen", "Caye Caulker"],
    "Benin": ["Porto-Novo", "Cotonou", "Djougou", "Parakou", "Bohicon", "Abomey", "Ouidah", "Natitingou", "Tanguieta", "Kandi"],
    "Bhutan": ["Thimphu", "Phuntsholing", "Punakha", "Jakar", "Paro", "Gelegphu", "Mongar", "Trongsa", "Samdrup Jongkhar", "Bumthang"],
    "Bolivia": ["Sucre", "La Paz", "Santa Cruz", "Cochabamba", "Oruro", "Potosí", "Tarija", "Chuquisaca", "El Alto", "Trinidad"],
    "Bosnia and Herzegovina": ["Sarajevo", "Banja Luka", "Mostar", "Zenica", "Tuzla", "Sarajevo", "Tuzla", "Zenica", "Mostar", "Zenica"],
    "Botswana": ["Gaborone", "Francistown", "Molepolole", "Maun", "Selibe-Phikwe", "Palapye", "Jwaneng", "Serowe", "Tlokweng", "Kasane"],
    "Brazil": ["Brasília", "Rio de Janeiro", "São Paulo", "Salvador", "Fortaleza", "Belo Horizonte", "Manaus", "Curitiba", "Recife", "Porto Alegre"],
    "Brunei": ["Bandar Seri Begawan", "Kuala Belait", "Seria", "Tutong", "Bangar", "Muara", "Belait", "Rimba", "Tungku", "Panchor"],
    "Bulgaria": ["Sofia", "Plovdiv", "Varna", "Burgas", "Ruse", "Stara Zagora", "Pleven", "Sliven", "Dobrich", "Shumen"],
    "Burkina Faso": ["Ouagadougou", "Bobo-Dioulasso", "Koudougou", "Banfora", "Ouahigouya", "Tenkodogo", "Ziniaré", "Koupéla", "Dédougou", "Manga"],
    "Burundi": ["Bujumbura", "Gitega", "Ngozi", "Ruyigi", "Cibitoke", "Makamba", "Muramvya", "Kayanza", "Muyinga", "Kirundo"],
    "Cabo Verde": ["Praia", "Mindelo", "Assomada", "São Filipe", "Porto Novo", "Ribeira Grande", "Santa Maria", "Tarrafal", "Calheta", "São Vicente"],
    "Cambodia": ["Phnom Penh", "Siem Reap", "Battambang", "Sihanoukville", "Kampong Cham", "Kampong Thom", "Koh Kong", "Kampot", "Takeo", "Pursat"],
    "Cameroon": ["Yaoundé", "Douala", "Bafoussam", "Garoua", "Kumba", "Maroua", "Nkongsamba", "Bertoua", "Ebolowa", "Kribi"],
    "Canada": ["Toronto", "Vancouver", "Montreal", "Calgary", "Ottawa", "Edmonton", "Winnipeg", "Quebec City", "Hamilton", "Kitchener"],
    "Central African Republic": ["Bangui", "Bimbo", "Berbérati", "Carnot", "Mbaïki", "Bouar", "Sibut", "Bossangoa", "Nola", "Kaga-Bandoro"],
    "Chad": ["N'Djamena", "Moundou", "Sarh", "Abéché", "Kélo", "Laï", "Chad", "Am Timan", "Tibesti", "Faya-Largeau"],
    "Chile": ["Santiago", "Valparaíso", "Concepción", "La Serena", "Antofagasta", "Temuco", "Rancagua", "Talca", "Arica", "Iquique"],
    "China": ["Beijing", "Shanghai", "Guangzhou", "Shenzhen", "Chengdu", "Hong Kong", "Tianjin", "Wuhan", "Hangzhou", "Nanjing"],
    "Colombia": ["Bogotá", "Medellín", "Cali", "Barranquilla", "Cartagena", "Cúcuta", "Bucaramanga", "Pereira", "Santa Marta", "Manizales"],
    "Comoros": ["Moroni", "Moutsamoudou", "Fomboni", "Domoni", "Sima", "Dzaoudzi", "Itsandra", "Ouani", "Chiconi", "Tsimkoura"],
    "Congo (Congo-Brazzaville)": ["Brazzaville", "Pointe-Noire", "Dolisie", "Oyo", "Nkayi", "Madingou", "Owando", "Makoua", "Kinkala", "Mossendjo"],
    "Congo (Democratic Republic)": ["Kinshasa", "Lubumbashi", "Mbuji-Mayi", "Kisangani", "Kananga", "Masina", "Bukavu", "Goma", "Kolwezi", "Tshikapa"],
    "Costa Rica": ["San José", "Alajuela", "Cartago", "Heredia", "Puntarenas", "Liberia", "San Isidro", "Tibas", "Escazu", "Santa Ana"],
    "Croatia": ["Zagreb", "Split", "Rijeka", "Osijek", "Zadar", "Velika Gorica", "Dubrovnik", "Sibenik", "Pula", "Karlovac"],
    "Cuba": ["Havana", "Santiago de Cuba", "Camagüey", "Holguín", "Santa Clara", "Guantánamo", "Las Tunas", "Cienfuegos", "Bayamo", "Pinar del Río"],
    "Cyprus": ["Nicosia", "Limassol", "Larnaca", "Famagusta", "Paphos", "Kyrenia", "Paralimni", "Ayia Napa", "Kofinou", "Deryneia"],
    "Czech Republic (Czechia)": ["Prague", "Brno", "Ostrava", "Plzeň", "Liberec", "Olomouc", "Hradec Králové", "Pardubice", "Zlín", "Ústí nad Labem"],
    "Denmark": ["Copenhagen", "Aarhus", "Odense", "Aalborg", "Esbjerg", "Randers", "Kolding", "Horsens", "Vejle", "Roskilde"],
    "Djibouti": ["Djibouti", "Ali Sabieh", "Tadjourah", "Dikhil", "Arta", "Obock", "Balho", "Chabelley", "Douda", "Holhol"],
    "Dominica": ["Roseau", "Portsmouth", "Marigot", "La Plaine", "Soufrière", "Castle Bruce", "Good Hope", "Grand Bay", "St. Joseph", "Mahaut"],
    "Dominican Republic": ["Santo Domingo", "Santiago", "La Romana", "San Pedro de Macorís", "San Francisco de Macorís", "Puerto Plata", "Higuey", "Moca", "Boca Chica", "San Cristóbal"],
    "Ecuador": ["Quito", "Guayaquil", "Cuenca", "Santo Domingo", "Machala", "Durán", "Ambato", "Loja", "Portoviejo", "Riobamba"],
    "Egypt": ["Cairo", "Alexandria", "Giza", "Shubra El Kheima", "Port Said", "Suez", "Mansoura", "Tanta", "Asyut", "Ismailia"],
    "El Salvador": ["San Salvador", "Santa Ana", "San Miguel", "Mejicanos", "Soyapango", "Ahuachapan", "La Libertad", "Chalatenango", "Usulután", "Sonsonate"],
    "Equatorial Guinea": ["Malabo", "Bata", "Ebebiyin", "Aconibe", "Evinayong", "Luba", "Riaba", "Mikomeseng", "Cogo", "Nsok-Nsomo"],
    "Eritrea": ["Asmara", "Mendefera", "Keren", "Massawa", "Decamhare", "Nakfa", "Barentu", "Teseney", "Adi Quala", "Sawa"],
    "Estonia": ["Tallinn", "Tartu", "Narva", "Pärnu", "Kohtla-Järve", "Jõhvi", "Viljandi", "Rakvere", "Valga", "Paide"],
    "Eswatini": ["Mbabane", "Manzini", "Big Bend", "Nhlangano", "Pigg's Peak", "Lobamba", "Siteki", "Hlatikulu", "Mhlume", "Siphofaneni"],
    "Ethiopia": ["Addis Ababa", "Dire Dawa", "Mekele", "Bahir Dar", "Gondar", "Hawassa", "Jimma", "Awassa", "Debre Markos", "Adama"],
    "Fiji": ["Suva", "Lautoka", "Nadi", "Labasa", "Ba", "Sigatoka", "Rakiraki", "Levuka", "Tavua", "Korovou"],
    "Finland": ["Helsinki", "Espoo", "Tampere", "Vantaa", "Oulu", "Turku", "Jyväskylä", "Lahti", "Kuopio", "Pori"],
    "France": ["Paris", "Marseille", "Lyon", "Toulouse", "Nice", "Nantes", "Montpellier", "Strasbourg", "Bordeaux", "Lille"],
    "Gabon": ["Libreville", "Port-Gentil", "Franceville", "Moanda", "Oyayé", "Tchibanga", "Makokou", "Mouila", "Lambaréné", "Bitam"],
    "Gambia": ["Banjul", "Serekunda", "Brikama", "Bakau", "Latri Kunda", "Mansakonko", "Farafenni", "Kerewan", "Koina", "Janjanbureh"],
    "Georgia": ["Tbilisi", "Batumi", "Kutaisi", "Zugdidi", "Rustavi", "Zestaponi", "Gori", "Khashuri", "Senaki", "Telavi"],
    "Germany": ["Berlin", "Hamburg", "Munich", "Cologne", "Frankfurt", "Stuttgart", "Düsseldorf", "Dortmund", "Essen", "Leipzig"],
    "Ghana": ["Accra", "Kumasi", "Tamale", "Sekondi-Takoradi", "Ashaiman", "Cape Coast", "Takoradi", "Ho", "Sunyani", "Koforidua"],
    "Greece": ["Athens", "Thessaloniki", "Patras", "Heraklion", "Larissa", "Volos", "Ioannina", "Chania", "Rhodes", "Kavala"],
    "Grenada": ["St. George's", "Gouyave", "Grenville", "Victoria", "Salisbury", "Munich", "Tanteen", "La Digue", "Carenage", "Beausejour"],
    "Guatemala": ["Guatemala City", "Mixco", "Villa Nueva", "Quetzaltenango", "Escuintla", "Mazatenango", "Cobán", "Chimaltenango", "Puerto Barrios", "Santa Catarina Pinula"],
    "Guinea": ["Conakry", "Nzérékoré", "Kankan", "Kindia", "Labé", "Faranah", "Boké", "Macenta", "Pita", "Kérouané"],
    "Guinea-Bissau": ["Bissau", "Bafata", "Gabú", "Canchungo", "Mansôa", "Cacheu", "Biombo", "Bolama", "Farim", "Tombali"],
    "Guyana": ["Georgetown", "Linden", "New Amsterdam", "Rosignol", "Skeldon", "Parika", "Bartica", "Anna Regina", "Mahdia", "Hubu"],
    "Haiti": ["Port-au-Prince", "Cap-Haïtien", "Hinch", "Petionville", "Jacmel", "Les Cayes", "Gonaïves", "P-au-P", "Miragoâne", "Verrettes"],
    "Honduras": ["Tegucigalpa", "San Pedro Sula", "Choloma", "La Ceiba", "El Progreso", "Comayagua", "Danlí", "Juticalpa", "Tocoa", "Santa Rosa de Copán"],
    "Hungary": ["Budapest", "Debrecen", "Szeged", "Miskolc", "Pécs", "Pápa", "Nyíregyháza", "Kecskemét", "Székesfehérvár", "Szombathely"],
    "Iceland": ["Reykjavik", "Kopavogur", "Reykjanesbær", "Akureyri", "Hafnarfjordur", "Reykholt", "Selfoss", "Egilsstaðir", "Isafjordur", "Akranes"],
    "India": ["Mumbai", "Delhi", "Bangalore", "Kolkata", "Chennai", "Hyderabad", "Ahmedabad", "Pune", "Surat", "Jaipur"],
    "Indonesia": ["Jakarta", "Surabaya", "Bandung", "Medan", "Bekasi", "Palembang", "Makassar", "Tangerang", "Semarang", "Malang"],
    "Iran": ["Tehran", "Mashhad", "Isfahan", "Karaj", "Shiraz", "Tabriz", "Ahvaz", "Qom", "Kermanshah", "Urmia"],
    "Iraq": ["Baghdad", "Basra", "Mosul", "Erbil", "Sulaymaniyah", "Najaf", "Karbala", "Kirkuk", "Duhok", "Samarra"],
    "Ireland": ["Dublin", "Cork", "Limerick", "Galway", "Waterford", "Dundalk", "Bray", "Swords", "Kilkenny", "Tralee"],
    "Israel": ["Jerusalem", "Tel Aviv", "Haifa", "Rishon Lezion", "Petah Tikva", "Ashdod", "Netanya", "Beersheba", "Bnei Brak", "Holon"],
    "Italy": ["Rome", "Milan", "Naples", "Turin", "Palermo", "Genoa", "Bologna", "Florence", "Bari", "Catania"],
    "Jamaica": ["Kingston", "Montego Bay", "Spanish Town", "Mandeville", "Portmore", "Ocho Rios", "May Pen", "Linstead", "Savanna-la-Mar", "Negril"],
    "Japan": ["Tokyo", "Yokohama", "Osaka", "Nagoya", "Sapporo", "Fukuoka", "Kobe", "Kawasaki", "Saitama", "Hiroshima"],
    "Jordan": ["Amman", "Zarqa", "Irbid", "Aqaba", "Mafraq", "Russeifa", "Salt", "Ma'an", "Karak", "Tafila"],
    "Kazakhstan": ["Almaty", "Nur-Sultan", "Shymkent", "Karaganda", "Aktobe", "Taraz", "Pavlodar", "Semey", "Kostanay", "Kyzylorda"],
    "Kenya": ["Nairobi", "Mombasa", "Nakuru", "Kisumu", "Eldoret", "Meru", "Thika", "Malindi", "Garissa", "Embu"],
    "Kiribati": ["Bairiki", "Betio", "Teaoraereke", "Tepuka", "Ambo", "Tabiteuea", "Abaiang", "Kuria", "Butaritari", "Marakei"],
    "Korea (North)": ["Pyongyang", "Hamhung", "Chongjin", "Nampo", "Sinuiju", "Wonsan", "Pyongsong", "Kaechon", "Kimchaek", "Sariwon"],
    "Korea (South)": ["Seoul", "Busan", "Incheon", "Daegu", "Daejeon", "Gwangju", "Suwon", "Ulsan", "Changwon", "Goyang"],
    "Kuwait": ["Kuwait City", "Al Ahmadi", "Hawalli", "Mubarak Al Kabeer", "Al Farwaniyah", "Al Jahra", "Salmiya", "Fahaheel", "Khaithan", "Rumaithiya"],
    "Kyrgyzstan": ["Bishkek", "Osh", "Jalal-Abad", "Tokmok", "Karakol", "Kadamjay", "Naryn", "Batken", "Kyzyl-Kiya", "Talas"],
    "Laos": ["Vientiane", "Savannakhet", "Pakse", "Luang Prabang", "Thakhek", "Xieng Khouang", "Phonsavan", "Muang Xay", "Attapeu", "Bokeo"],
    "Latvia": ["Riga", "Daugavpils", "Jurmala", "Jelgava", "Jurmala", "Ventspils", "Liepaja", "Jurmala", "Rezekne", "Jurmala"],
    "Lebanon": ["Beirut", "Tripoli", "Sidon", "Tyre", "Zahle", "Byblos", "Baalbek", "Nabatieh", "Bekaa", "Batroun"],
    "Lesotho": ["Maseru", "Teyateyaneng", "Maputsoe", "Mohale's Hoek", "Quthing", "Qacha's Nek", "Mokhotlong", "Butha-Buthe", "Hlotse", "Leribe"],
    "Liberia": ["Monrovia", "Gbarnga", "Buchanan", "Zwedru", "Harper", "Robertsport", "Voinjama", "Toe Town", "Yekepa", "Kakata"],
    "Libya": ["Tripoli", "Benghazi", "Misrata", "Zawiya", "Tarhuna", "Al Bayda", "Sebha", "Derna", "Bani Walid", "Khoms"],
    "Liechtenstein": ["Vaduz", "Schaan", "Balzers", "Eschen", "Mauren", "Balzers", "Gamprin", "Schellenberg", "Bendern", "Planken"],
    "Lithuania": ["Vilnius", "Kaunas", "Klaipėda", "Šiauliai", "Panevėžys", "Alytus", "Marijampolė", "Jonava", "Utena", "Telšiai"],
    "Luxembourg": ["Luxembourg City", "Ettelbruck", "Differdange", "Ettelbruck", "Dudelange", "Ettelbruck", "Remich", "Bissen", "Mersch", "Ettelbruck"],
    "Madagascar": ["Antananarivo", "Toamasina", "Antsirabe", "Fianarantsoa", "Mahajanga", "Toliara", "Maroantsetra", "Manakara", "Ambatolampy", "Sambava"],
    "Malawi": ["Lilongwe", "Blantyre", "Mzuzu", "Zomba", "Mangochi", "Kasungu", "Liwonde", "Chiradzulu", "Dedza", "Rumphi"],
    "Malaysia": ["Kuala Lumpur", "George Town", "Johor Bahru", "Kota Kinabalu", "Ipoh", "Shah Alam", "Kuching", "Alor Setar", "Melaka", "Petaling Jaya"],
    "Maldives": ["Malé", "Addu City", "Fuvahmulah", "Hinnavaru", "Dhidhdhoo", "Kulhudhuffushi", "Thulusdhoo", "Villingili", "Maafushi", "Dharavandhoo"],
    "Mali": ["Bamako", "Segou", "Mopti", "Kayes", "Koulikoro", "Tombouctou", "Gao", "Kidal", "Sikasso", "Markala"],
    "Malta": ["Valletta", "Mosta", "Birkirkara", "Mellieha", "Sliema", "St. Julian's", "Rabat", "Gozo", "Qormi", "Floriana"],
    "Marshall Islands": ["Majuro", "Ebeye", "Arno", "Wotje", "Kwajalein", "Rongelap", "Mili", "Ailuk", "Bikar", "Enewetak"],
    "Mauritania": ["Nouakchott", "Nouadhibou", "Kiffa", "Rosso", "Atar", "Néma", "Zouérat", "Akjoujt", "Aleg", "Boutilimit"],
    "Mauritius": ["Port Louis", "Beau Bassin-Rose Hill", "Curepipe", "Vacoas-Phoenix", "Quatre Bornes", "Bambous", "Triolet", "Souillac", "Grand Baie", "Mahebourg"],
    "Mexico": ["Mexico City", "Guadalajara", "Monterrey", "Puebla", "Tijuana", "León", "Cancún", "Mérida", "Chihuahua", "Juárez"],
    "Micronesia": ["Palikir", "Weno", "Kolonia", "Pohnpei", "Chuuk", "Kosrae", "Yap", "Saipan", "Tinian", "Rota"],
    "Moldova": ["Chișinău", "Tiraspol", "Bălți", "Bender", "Briceni", "Orhei", "Cahul", "Ungheni", "Edineț", "Soroca"],
    "Monaco": ["Monaco", "La Condamine", "Moneghetti", "Fontvieille", "Les Révoires", "Saint-Roman", "Montaigne", "Carabiniers", "Spélugues", "Cimitière"],
    "Mongolia": ["Ulaanbaatar", "Erdenet", "Darkhan", "Choibalsan", "Mörön", "Sühbaatar", "Bayan-Ölgii", "Ölgii", "Zuunmod", "Arvaikheer"],
    "Montenegro": ["Podgorica", "Nikšić", "Herceg Novi", "Bijelo Polje", "Pljevlja", "Berane", "Rožaje", "Danilovgrad", "Cetinje", "Kotor"],
    "Morocco": ["Casablanca", "Rabat", "Marrakech", "Fes", "Tangier", "Agadir", "Meknes", "Oujda", "Temara", "Safi"],
    "Mozambique": ["Maputo", "Beira", "Nampula", "Chimoio", "Nacala", "Tete", "Quelimane", "Pemba", "Matola", "Inhambane"],
    "Myanmar": ["Yangon", "Mandalay", "Naypyidaw", "Monywa", "Bago", "Taunggyi", "Magway", "Mawlamyine", "Pakokku", "Pyay"],
    "Namibia": ["Windhoek", "Walvis Bay", "Swakopmund", "Rundu", "Oshakati", "Ongwediva", "Grootfontein", "Luderitz", "Keetmanshoop", "Rehoboth"],
    "Nauru": ["Yaren", "Meneng", "Baitsi", "Anabar", "Aiwo", "Uaboe", "Boe", "Nijumeang", "Ewa", "Anetan"],
    "Nepal": ["Kathmandu", "Pokhara", "Lalitpur", "Biratnagar", "Birgunj", "Bharatpur", "Janakpur", "Dharan", "Hetauda", "Butwal"],
    "Netherlands": ["Amsterdam", "Rotterdam", "The Hague", "Utrecht", "Eindhoven", "Tilburg", "Groningen", "Almere", "Breda", "Nijmegen"],
    "New Zealand": ["Auckland", "Wellington", "Christchurch", "Hamilton", "Dunedin", "Tauranga", "Napier-Hastings", "Palmerston North", "Rotorua", "New Plymouth"],
    "Nicaragua": ["Managua", "León", "Masaya", "Chinandega", "Granada", "Estelí", "Juigalpa", "Matagalpa", "Bluefields", "Rivas"],
    "Niger": ["Niamey", "Zinder", "Maradi", "Tahoua", "Agadez", "Tillabéri", "Dosso", "Tessaoua", "Arlit", "Diffa"],
    "Nigeria": ["Lagos", "Kano", "Ibadan", "Abuja", "Port Harcourt", "Benin City", "Kaduna", "Maiduguri", "Zaria", "Aba"],
    "North Macedonia": ["Skopje", "Bitola", "Prilep", "Tetovo", "Veles", "Ohrid", "Kumanovo", "Stip", "Strumica", "Kavadarci"],
    "Norway": ["Oslo", "Bergen", "Stavanger", "Drammen", "Fredrikstad", "Dønski", "Skien", "Sarpsborg", "Sandnes", "Trondheim"],
    "Oman": ["Muscat", "Salalah", "Sohar", "Nizwa", "Barka", "Ibra", "Ibri", "Sur", "Manah", "Rustaq"],
    "Pakistan": ["Karachi", "Lahore", "Islamabad", "Faisalabad", "Rawalpindi", "Multan", "Sialkot", "Sukkur", "Quetta", "Peshawar"],
    "Palau": ["Ngerulmud", "Melekeok", "Koror", "Angaur", "Kayangel", "Babeldaob", "Sonsorol", "Peleliu", "Hatohobei", "Melekeok"],
    "Panama": ["Panama City", "San Miguelito", "David", "Colón", "La Chorrera", "Chitré", "Santiago de Veraguas", "Penonomé", "Penonomé", "Las Tablas"],
    "Papua New Guinea": ["Port Moresby", "Lae", "Madang", "Mount Hagen", "Goroka", "Kokopo", "Popondetta", "Kimbe", "Wewak", "Buka"],
    "Paraguay": ["Asunción", "Ciudad del Este", "San Lorenzo", "Luque", "Capiatá", "Lambaré", "Fernando de la Mora", "Pedro Juan Caballero", "Encarnación", "Villarrica"],
    "Peru": ["Lima", "Arequipa", "Trujillo", "Chiclayo", "Piura", "Iquitos", "Cuzco", "Chimbote", "Tacna", "Huancayo"],
    "Philippines": ["Quezon City", "Manila", "Davao City", "Cebu City", "Zamboanga City", "Antipolo", "Taguig", "Pasig", "Cagayan de Oro", "Dumaguete"],
    "Poland": ["Warsaw", "Kraków", "Łódź", "Wrocław", "Poznań", "Gdańsk", "Szczecin", "Bydgoszcz", "Lublin", "Katowice"],
    "Portugal": ["Lisbon", "Porto", "Amadora", "Braga", "Coimbra", "Agualva-Cacém", "Setúbal", "Évora", "Funchal", "Leiria"],
    "Qatar": ["Doha", "Al Rayyan", "Al Wakrah", "Al Khor", "Ar Rayyan", "Umm Salal", "Al Daayen", "Al Shahaniya", "Al Jumayl", "Madinat ash Shamal"],
    "Romania": ["Bucharest", "Cluj-Napoca", "Timișoara", "Iași", "Constanța", "Craiova", "Galați", "Brașov", "Ploiești", "Oradea"],
    "Russia": ["Moscow", "Saint Petersburg", "Novosibirsk", "Yekaterinburg", "Nizhny Novgorod", "Kazan", "Chelyabinsk", "Omsk", "Samara", "Rostov-on-Don"],
    "Rwanda": ["Kigali", "Butare", "Gisenyi", "Musanze", "Rubavu", "Huye", "Nyamata", "Ruhengeri", "Kibuye", "Gikongoro"],
    "Saint Kitts and Nevis": ["Basseterre", "Charlestown", "Cayon", "Sandy Point", "Butlers", "Shadwell", "Dieppe Bay Town", "Nevis", "Cades Bay", "Cotton Ground"],
    "Saint Lucia": ["Castries", "Vieux Fort", "Gros Islet", "Soufrière", "Dennery", "Laborie", "Anse-la-Raye", "Micoud", "Canaries", "Babonneau"],
    "Saint Vincent and the Grenadines": ["Kingstown", "Barrouallie", "Bequia", "Port Elizabeth", "Sandy Bay", "Biabou", "Chateaubelair", "Calliaqua", "Canouan", "Union Island"],
    "Samoa": ["Apia", "Vaitele", "Lepea", "Lalomanu", "Salelologa", "Faleasiu", "Fagalii", "A'ufaga", "Apia", "Vaitogi"],
    "San Marino": ["San Marino", "Serravalle", "Borgo Maggiore", "Domagnano", "Fiorentino", "Acquaviva", "Chiesanuova", "Montegiardino", "Città di San Marino", "Faetano"],
    "São Tomé and Príncipe": ["São Tomé", "Neves", "Santana", "Trindade", "Água Grande", "São João", "Guadalupe", "Santa Catarina", "Caiçara", "Príncipe"],
    "Saudi Arabia": ["Riyadh", "Jeddah", "Mecca", "Medina", "Dammam", "Khobar", "Tabuk", "Buraidah", "Al Khobar", "Hail"],
    "Senegal": ["Dakar", "Touba", "Kaolack", "Ziguinchor", "Saint-Louis", "Thiès", "Mbour", "Kolda", "Fatick", "Diourbel"],
    "Serbia": ["Belgrade", "Novi Sad", "Niš", "Kragujevac", "Subotica", "Zrenjanin", "Kragujevac", "Leskovac", "Vranje", "Senta"],
    "Seychelles": ["Victoria", "Anse Boileau", "Anse Royale", "Beau Vallon", "Pointe Larue", "Grand Anse", "Takamaka", "Mont Fleuri", "La Digue", "Praslin"],
    "Sierra Leone": ["Freetown", "Bo", "Kenema", "Makeni", "Koidu", "Kailahun", "Moyamba", "Bonthe", "Pujehun", "Port Loko"],
    "Singapore": ["Singapore", "Bukit Panjang", "Sengkang", "Yishun", "Jurong West", "Bedok", "Woodlands", "Toa Payoh", "Ang Mo Kio", "Tampines"],
    "Slovakia": ["Bratislava", "Košice", "Prešov", "Nitra", "Trnava", "Žilina", "Martin", "Trenčín", "Poprad", "Prievidza"],
    "Slovenia": ["Ljubljana", "Maribor", "Celje", "Kranj", "Koper", "Novo Mesto", "Velenje", "Murska Sobota", "Ptuj", "Jesenice"],
    "Solomon Islands": ["Honiara", "Auki", "Gizo", "Munda", "Kavieng", "Noro", "Tulagi", "Buala", "Lata", "Malaita"],
    "Somalia": ["Mogadishu", "Hargeisa", "Bosaso", "Kismayo", "Merca", "Baidoa", "Galkayo", "Burao", "Jowhar", "Qardho"],
    "South Africa": ["Johannesburg", "Cape Town", "Durban", "Pretoria", "Port Elizabeth", "Bloemfontein", "East London", "Polokwane", "Pietermaritzburg", "Kimberley"],
    "South Korea": ["Seoul", "Busan", "Incheon", "Daegu", "Daejeon", "Gwangju", "Ulsan", "Suwon", "Changwon", "Goyang"],
    "South Sudan": ["Juba", "Malakal", "Wau", "Rumbek", "Aweil", "Bentiu", "Bor", "Yambio", "Torit", "Yei"],
    "Spain": ["Madrid", "Barcelona", "Valencia", "Seville", "Zaragoza", "Málaga", "Murcia", "Palma de Mallorca", "Las Palmas", "Bilbao"],
    "Sri Lanka": ["Colombo", "Kandy", "Galle", "Jaffna", "Kurunegala", "Anuradhapura", "Negombo", "Trincomalee", "Matara", "Batticaloa"],
    "Sudan": ["Khartoum", "Omdurman", "Port Sudan", "Nyala", "El-Obeid", "Kassala", "Al Qadarif", "Sennar", "Wad Madani", "Kosti"],
    "Suriname": ["Paramaribo", "Nieuw Nickerie", "Moengo", "Lelydorp", "Boven Corantijn", "Albina", "Marienburg", "Peyre", "Stoelmanseiland", "Nickerie"],
    "Sweden": ["Stockholm", "Gothenburg", "Malmö", "Uppsala", "Västerås", "Örebro", "Linköping", "Helsingborg", "Jönköping", "Norrköping"],
    "Switzerland": ["Zurich", "Geneva", "Basel", "Bern", "Lucerne", "Lausanne", "St. Gallen", "Lugano", "Zurich", "Winterthur"],
    "Syria": ["Damascus", "Aleppo", "Homs", "Latakia", "Hama", "Tartus", "Daraa", "Deir ez-Zor", "Raqqa", "Idlib"],
    "Taiwan": ["Taipei", "Kaohsiung", "Taichung", "Tainan", "Taipei City", "Keelung", "Hsinchu", "Chiayi", "Taoyuan", "Changhua"],
    "Tajikistan": ["Dushanbe", "Khujand", "Kulob", "Khorugh", "Isfara", "Bokhtar", "Tursunzoda", "Qurghonteppa", "Vahdat", "Panji Poyon"],
    "Tanzania": ["Dar es Salaam", "Mwanza", "Arusha", "Dodoma", "Mbeya", "Moshi", "Tanga", "Zanzibar City", "Morogoro", "Mtwara"],
    "Thailand": ["Bangkok", "Nonthaburi", "Nakhon Ratchasima", "Chiang Mai", "Chonburi", "Hat Yai", "Khon Kaen", "Nakhon Si Thammarat", "Udon Thani", "Phuket"],
    "Timor-Leste": ["Dili", "Baucau", "Viqueque", "Maliana", "Lospalos", "Suai", "Aileu", "Ermera", "Bobonaro", "Atauro"],
    "Togo": ["Lomé", "Sokodé", "Kara", "Atakpamé", "Tchamba", "Bassar", "Kpalimé", "Vogan", "Tsévié", "Dapaong"],
    "Tonga": ["Nukuʻalofa", "Neiafu", "Vavaʻu", "Haveluloto", "Kanokupolu", "Pangai", "Haʻapai", "Muʻa", "Fuaʻamotu", "Kolomotuʻa"],
    "Trinidad and Tobago": ["Port of Spain", "San Fernando", "Scarborough", "Chaguanas", "Arima", "Point Fortin", "Pointe-a-Pierre", "San Juan", "St. Augustine", "Tunapuna"],
    "Tunisia": ["Tunis", "Sfax", "Sousse", "Kairouan", "Gabès", "Ariana", "Bizert", "Nabeul", "Tozeur", "La Marsa"],
    "Turkey": ["Istanbul", "Ankara", "Izmir", "Bursa", "Antalya", "Adana", "Konya", "Gaziantep", "Mersin", "Kayseri"],
    "Turkmenistan": ["Ashgabat", "Mary", "Turkmenabat", "Dashoguz", "Balkanabat", "Bayramaly", "Kerki", "Serdar", "Merv", "Gypjak"],
    "Tuvalu": ["Funafuti", "Savave", "Vaiaku", "Fongafale", "Asau", "Nanumea", "Nanumaga", "Nukufetau", "Vaitupu", "Niutao"],
    "Uganda": ["Kampala", "Entebbe", "Mbarara", "Jinja", "Mbale", "Masaka", "Nansana", "Wakiso", "Kira", "Kiboga"],
    "Ukraine": ["Kyiv", "Kharkiv", "Odesa", "Dnipro", "Donetsk", "Zaporizhzhia", "Lviv", "Kryvyi Rih", "Mykolaiv", "Mariupol"],
    "United Arab Emirates": ["Dubai", "Abu Dhabi", "Sharjah", "Al Ain", "Ajman", "Umm Al-Quwain", "Fujairah", "Ras Al Khaimah", "Khalifa City", "Al Fujayrah"],
    "United Kingdom": ["London", "Birmingham", "Manchester", "Glasgow", "Leeds", "Liverpool", "Sheffield", "Edinburgh", "Bristol", "Cardiff"],
    "United States": ["New York City", "Los Angeles", "Chicago", "Houston", "Phoenix", "Philadelphia", "San Antonio", "San Diego", "Dallas", "San Jose"],
    "Uruguay": ["Montevideo", "Salto", "Paysandú", "Maldonado", "Tacuarembó", "Rivera", "Colonia del Sacramento", "San José de Mayo", "Durazno", "Canelones"],
    "Uzbekistan": ["Tashkent", "Samarkand", "Namangan", "Bukhara", "Andijan", "Nukus", "Fergana", "Khiva", "Termiz", "Jizzakh"],
    "Vanuatu": ["Port Vila", "Luganville", "Espiritu Santo", "Tanna", "Malekula", "Aneityum", "Emae", "Erromango", "Santo", "Paama"],
    "Vatican City": ["Vatican City", "St. Peter's Basilica", "Vatican Museums", "Sistine Chapel", "St. Peter's Square", "Vatican Gardens", "Apostolic Palace", "Castel Gandolfo", "Piazza del Sant'Uffizio", "Vatican Library"],
    "Venezuela": ["Caracas", "Maracaibo", "Valencia", "Barquisimeto", "Ciudad Guayana", "Mérida", "Maturín", "San Cristóbal", "Porlamar", "Puerto La Cruz"],
    "Vietnam": ["Ho Chi Minh City", "Hanoi", "Da Nang", "Hai Phong", "Can Tho", "Bien Hoa", "Hue", "Nha Trang", "Vinh", "Thanh Hoa"],
    "Yemen": ["Sana'a", "Aden", "Taiz", "Al Hudaydah", "Ibb", "Dhamar", "Mukalla", "Zabid", "Marib", "Hajjah"],
    "Zambia": ["Lusaka", "Kitwe", "Ndola", "Kabwe", "Chingola", "Livingstone", "Luanshya", "Mufulira", "Solwezi", "Kasama"],
    "Zimbabwe": ["Harare", "Bulawayo", "Chitungwiza", "Mutare", "Gweru", "Kwekwe", "Kadoma", "Masvingo", "Redcliff", "Epworth"]
};
