const realEstateData = [
    {
        "imgUrl": "https://via.placeholder.com/250",
        "title": "Luxury Villa in Luanda",
        "price": "$850,000",
        "description": "A modern 4-bedroom villa located in Luanda, offering stunning city views and top-tier amenities.",
        "address": "Luanda, Angola",
        "bedrooms": 4,
        "bathrooms": 3,
        "squareFeet": "3500",
        "yearBuilt": "2019",
        "propertyType": "Villa",
        "country": "Angola",
        "city": "Luanda",
        "priceRange": "500000 - 1,000,000",
        "squareFeetRange": "3000 - 5000 sq ft",
        "yearBuiltRange": "2011 - 2020",
        "parking": "Available",
        "garden": "Yes",
        "flooring": "Wood",
        "view": "City",
        "airConditioning": "Available",
        "heating": "Central",
        "pool": "Available",
        "balcony": "Available",
        "roof": "Flat",
        "security": "Available",
        "schools": "Yes",
        "internet": "Available",
        "gym": "Available",
        "storage": "Available",
        "shopping": "Close",
        "hospital": "Yes",
        "park": "Yes"
    },
    {
        "imgUrl": "https://via.placeholder.com/250",
        "title": "Modern Apartment in Luanda",
        "price": "$220,000",
        "description": "A spacious 2-bedroom apartment offering comfort and a prime location in Luanda.",
        "address": "Luanda, Angola",
        "bedrooms": 2,
        "bathrooms": 2,
        "squareFeet": "1200",
        "yearBuilt": "2015",
        "propertyType": "Apartment",
        "country": "Angola",
        "city": "Luanda",
        "priceRange": "200,000 - 300,000",
        "squareFeetRange": "1000 - 2000 sq ft",
        "yearBuiltRange": "2011 - 2020",
        "parking": "Not Available",
        "garden": "No",
        "flooring": "Tile",
        "view": "City",
        "airConditioning": "Available",
        "heating": "Individual",
        "pool": "Not Available",
        "balcony": "Not Available",
        "roof": "Sloped",
        "security": "Available",
        "schools": "No",
        "internet": "Available",
        "gym": "Not Available",
        "storage": "Not Available",
        "shopping": "Close",
        "hospital": "No",
        "park": "No"
    },
    {
        "imgUrl": "https://via.placeholder.com/250",
        "title": "Beachfront House in Saint John's",
        "price": "$1,200,000",
        "description": "A luxurious 5-bedroom house offering breathtaking ocean views and direct beach access.",
        "address": "Saint John's, Antigua and Barbuda",
        "bedrooms": 5,
        "bathrooms": 4,
        "squareFeet": "6000",
        "yearBuilt": "2021",
        "propertyType": "House",
        "country": "Antigua and Barbuda",
        "city": "Saint John's",
        "priceRange": "1,000,000 - 2,000,000",
        "squareFeetRange": "5000+ sq ft",
        "yearBuiltRange": "2021+",
        "parking": "Available",
        "garden": "Yes",
        "flooring": "Marble",
        "view": "Sea",
        "airConditioning": "Available",
        "heating": "Central",
        "pool": "Available",
        "balcony": "Available",
        "roof": "Flat",
        "security": "Available",
        "schools": "Yes",
        "internet": "Available",
        "gym": "Available",
        "storage": "Available",
        "shopping": "Close",
        "hospital": "Yes",
        "park": "Yes"
    },
    {
        "imgUrl": "https://via.placeholder.com/250",
        "title": "Cozy Condo in Saint John's",
        "price": "$180,000",
        "description": "A charming 1-bedroom condo with easy access to shops and public transport.",
        "address": "Saint John's, Antigua and Barbuda",
        "bedrooms": 1,
        "bathrooms": 1,
        "squareFeet": "800",
        "yearBuilt": "2010",
        "propertyType": "Condo",
        "country": "Antigua and Barbuda",
        "city": "Saint John's",
        "priceRange": "Up to 100,000",
        "squareFeetRange": "Up to 1000 sq ft",
        "yearBuiltRange": "Before 2000",
        "parking": "Not Available",
        "garden": "No",
        "flooring": "Carpet",
        "view": "City",
        "airConditioning": "Not Available",
        "heating": "Individual",
        "pool": "Not Available",
        "balcony": "Not Available",
        "roof": "Sloped",
        "security": "Not Available",
        "schools": "No",
        "internet": "Available",
        "gym": "Not Available",
        "storage": "Not Available",
        "shopping": "Close",
        "hospital": "No",
        "park": "No"
    },
    {
        "imgUrl": "https://via.placeholder.com/250",
        "title": "Spacious House in Buenos Aires",
        "price": "$950,000",
        "description": "A beautiful 4-bedroom house located in Buenos Aires, featuring modern amenities and a spacious garden.",
        "address": "Buenos Aires, Argentina",
        "bedrooms": 4,
        "bathrooms": 3,
        "squareFeet": "4500",
        "yearBuilt": "2018",
        "propertyType": "House",
        "country": "Argentina",
        "city": "Buenos Aires",
        "priceRange": "500,000 - 1,000,000",
        "squareFeetRange": "3000 - 5000 sq ft",
        "yearBuiltRange": "2011 - 2020",
        "parking": "Available",
        "garden": "Yes",
        "flooring": "Wood",
        "view": "Park",
        "airConditioning": "Available",
        "heating": "Central",
        "pool": "Available",
        "balcony": "Available",
        "roof": "Flat",
        "security": "Available",
        "schools": "Yes",
        "internet": "Available",
        "gym": "Available",
        "storage": "Available",
        "shopping": "Close",
        "hospital": "Yes",
        "park": "Yes"
    },
    {
        "imgUrl": "https://via.placeholder.com/250",
        "title": "Cozy Condo in Buenos Aires",
        "price": "$180,000",
        "description": "A 1-bedroom condo located in the heart of Buenos Aires, offering convenience and comfort.",
        "address": "Buenos Aires, Argentina",
        "bedrooms": 1,
        "bathrooms": 1,
        "squareFeet": "850",
        "yearBuilt": "2010",
        "propertyType": "Condo",
        "country": "Argentina",
        "city": "Buenos Aires",
        "priceRange": "Up to 100,000",
        "squareFeetRange": "Up to 1000 sq ft",
        "yearBuiltRange": "Before 2000",
        "parking": "Not Available",
        "garden": "No",
        "flooring": "Tile",
        "view": "City",
        "airConditioning": "Available",
        "heating": "Individual",
        "pool": "Not Available",
        "balcony": "Not Available",
        "roof": "Sloped",
        "security": "Available",
        "schools": "No",
        "internet": "Available",
        "gym": "Not Available",
        "storage": "Not Available",
        "shopping": "Close",
        "hospital": "No",
        "park": "No"
    },
    {
        "imgUrl": "https://via.placeholder.com/250",
        "title": "Stylish Apartment in Yerevan",
        "price": "$220,000",
        "description": "A modern 2-bedroom apartment in the center of Yerevan, offering convenience and contemporary style.",
        "address": "Yerevan, Armenia",
        "bedrooms": 2,
        "bathrooms": 2,
        "squareFeet": "1200",
        "yearBuilt": "2015",
        "propertyType": "Apartment",
        "country": "Armenia",
        "city": "Yerevan",
        "priceRange": "200,000 - 300,000",
        "squareFeetRange": "1000 - 2000 sq ft",
        "yearBuiltRange": "2011 - 2020",
        "parking": "Available",
        "garden": "No",
        "flooring": "Tile",
        "view": "City",
        "airConditioning": "Available",
        "heating": "Individual",
        "pool": "Not Available",
        "balcony": "Not Available",
        "roof": "Flat",
        "security": "Available",
        "schools": "Yes",
        "internet": "Available",
        "gym": "Not Available",
        "storage": "Not Available",
        "shopping": "Close",
        "hospital": "Yes",
        "park": "No"
    },
    {
        "imgUrl": "https://via.placeholder.com/250",
        "title": "Luxury Villa in Yerevan",
        "price": "$1,500,000",
        "description": "A stunning 5-bedroom villa located in Yerevan, offering mountain views and world-class amenities.",
        "address": "Yerevan, Armenia",
        "bedrooms": 5,
        "bathrooms": 4,
        "squareFeet": "5500",
        "yearBuilt": "2022",
        "propertyType": "Villa",
        "country": "Armenia",
        "city": "Yerevan",
        "priceRange": "1,000,000 - 2,000,000",
        "squareFeetRange": "5000+ sq ft",
        "yearBuiltRange": "2021+",
        "parking": "Available",
        "garden": "Yes",
        "flooring": "Wood",
        "view": "Mountain",
        "airConditioning": "Available",
        "heating": "Central",
        "pool": "Available",
        "balcony": "Available",
        "roof": "Flat",
        "security": "Available",
        "schools": "Yes",
        "internet": "Available",
        "gym": "Available",
        "storage": "Available",
        "shopping": "Close",
        "hospital": "Yes",
        "park": "Yes"
    },
    {
        "imgUrl": "https://via.placeholder.com/250",
        "title": "Modern Beachfront Villa in Sydney",
        "price": "$2,800,000",
        "description": "A luxurious 6-bedroom villa located on the beachfront in Sydney, with breathtaking sea views and private access.",
        "address": "Sydney, Australia",
        "bedrooms": 6,
        "bathrooms": 5,
        "squareFeet": "8000",
        "yearBuilt": "2023",
        "propertyType": "Villa",
        "country": "Australia",
        "city": "Sydney",
        "priceRange": "2,000,000+",
        "squareFeetRange": "5000+ sq ft",
        "yearBuiltRange": "2021+",
        "parking": "Available",
        "garden": "Yes",
        "flooring": "Marble",
        "view": "Sea",
        "airConditioning": "Available",
        "heating": "Central",
        "pool": "Available",
        "balcony": "Available",
        "roof": "Flat",
        "security": "Available",
        "schools": "Yes",
        "internet": "Available",
        "gym": "Available",
        "storage": "Available",
        "shopping": "Close",
        "hospital": "Yes",
        "park": "Yes"
    },
    {
        "imgUrl": "https://via.placeholder.com/250",
        "title": "Charming Apartment in Melbourne",
        "price": "$500,000",
        "description": "A cozy 2-bedroom apartment with city views in Melbourne, offering a perfect blend of convenience and comfort.",
        "address": "Melbourne, Australia",
        "bedrooms": 2,
        "bathrooms": 1,
        "squareFeet": "1200",
        "yearBuilt": "2016",
        "propertyType": "Apartment",
        "country": "Australia",
        "city": "Melbourne",
        "priceRange": "300,000 - 500,000",
        "squareFeetRange": "1000 - 2000 sq ft",
        "yearBuiltRange": "2011 - 2020",
        "parking": "Not Available",
        "garden": "No",
        "flooring": "Carpet",
        "view": "City",
        "airConditioning": "Available",
        "heating": "Individual",
        "pool": "Not Available",
        "balcony": "Not Available",
        "roof": "Sloped",
        "security": "Available",
        "schools": "Yes",
        "internet": "Available",
        "gym": "Not Available",
        "storage": "Not Available",
        "shopping": "Close",
        "hospital": "No",
        "park": "No"
    },
    {
        "imgUrl": "https://via.placeholder.com/250",
        "title": "Modern Condo in Vienna",
        "price": "$450,000",
        "description": "A stylish 2-bedroom condo located in the heart of Vienna, offering a contemporary living experience.",
        "address": "Vienna, Austria",
        "bedrooms": 2,
        "bathrooms": 2,
        "squareFeet": "1000",
        "yearBuilt": "2018",
        "propertyType": "Condo",
        "country": "Austria",
        "city": "Vienna",
        "priceRange": "300,000 - 500,000",
        "squareFeetRange": "1000 - 2000 sq ft",
        "yearBuiltRange": "2011 - 2020",
        "parking": "Available",
        "garden": "No",
        "flooring": "Wood",
        "view": "City",
        "airConditioning": "Available",
        "heating": "Central",
        "pool": "Not Available",
        "balcony": "Not Available",
        "roof": "Sloped",
        "security": "Available",
        "schools": "Yes",
        "internet": "Available",
        "gym": "Not Available",
        "storage": "Available",
        "shopping": "Close",
        "hospital": "Yes",
        "park": "No"
    },
    {
        "imgUrl": "https://via.placeholder.com/250",
        "title": "Luxury Villa in Vienna",
        "price": "$3,200,000",
        "description": "A lavish 5-bedroom villa with panoramic views of Vienna, perfect for those seeking high-end living.",
        "address": "Vienna, Austria",
        "bedrooms": 5,
        "bathrooms": 4,
        "squareFeet": "6500",
        "yearBuilt": "2021",
        "propertyType": "Villa",
        "country": "Austria",
        "city": "Vienna",
        "priceRange": "2,000,000+",
        "squareFeetRange": "5000+ sq ft",
        "yearBuiltRange": "2021+",
        "parking": "Available",
        "garden": "Yes",
        "flooring": "Marble",
        "view": "City",
        "airConditioning": "Available",
        "heating": "Central",
        "pool": "Available",
        "balcony": "Available",
        "roof": "Flat",
        "security": "Available",
        "schools": "Yes",
        "internet": "Available",
        "gym": "Available",
        "storage": "Available",
        "shopping": "Close",
        "hospital": "Yes",
        "park": "Yes"
    },
    {
        "imgUrl": "https://via.placeholder.com/250",
        "title": "Stylish Apartment in Baku",
        "price": "$250,000",
        "description": "A cozy 1-bedroom apartment in the vibrant city of Baku, offering an ideal city living experience.",
        "address": "Baku, Azerbaijan",
        "bedrooms": 1,
        "bathrooms": 1,
        "squareFeet": "700",
        "yearBuilt": "2012",
        "propertyType": "Apartment",
        "country": "Azerbaijan",
        "city": "Baku",
        "priceRange": "Up to 100,000",
        "squareFeetRange": "Up to 1000 sq ft",
        "yearBuiltRange": "Before 2000",
        "parking": "Not Available",
        "garden": "No",
        "flooring": "Tile",
        "view": "City",
        "airConditioning": "Available",
        "heating": "Individual",
        "pool": "Not Available",
        "balcony": "Not Available",
        "roof": "Sloped",
        "security": "Available",
        "schools": "No",
        "internet": "Available",
        "gym": "Not Available",
        "storage": "Not Available",
        "shopping": "Close",
        "hospital": "No",
        "park": "No"
    },
    {
        "imgUrl": "https://via.placeholder.com/250",
        "title": "Oceanfront Villa in Baku",
        "price": "$1,800,000",
        "description": "A luxurious 4-bedroom villa with stunning views of the Caspian Sea, perfect for relaxation and entertainment.",
        "address": "Baku, Azerbaijan",
        "bedrooms": 4,
        "bathrooms": 3,
        "squareFeet": "5500",
        "yearBuilt": "2019",
        "propertyType": "Villa",
        "country": "Azerbaijan",
        "city": "Baku",
        "priceRange": "1,000,000 - 2,000,000",
        "squareFeetRange": "5000+ sq ft",
        "yearBuiltRange": "2011 - 2020",
        "parking": "Available",
        "garden": "Yes",
        "flooring": "Wood",
        "view": "Sea",
        "airConditioning": "Available",
        "heating": "Central",
        "pool": "Available",
        "balcony": "Available",
        "roof": "Flat",
        "security": "Available",
        "schools": "Yes",
        "internet": "Available",
        "gym": "Available",
        "storage": "Available",
        "shopping": "Close",
        "hospital": "Yes",
        "park": "Yes"
    },
    {
        "imgUrl": "https://via.placeholder.com/250",
        "title": "Luxury Beach House in Nassau",
        "price": "$3,000,000",
        "description": "A spectacular 5-bedroom beachfront house with panoramic views of the ocean, perfect for a tropical lifestyle.",
        "address": "Nassau, Bahamas",
        "bedrooms": 5,
        "bathrooms": 5,
        "squareFeet": "7000",
        "yearBuilt": "2020",
        "propertyType": "House",
        "country": "Bahamas",
        "city": "Nassau",
        "priceRange": "2,000,000+",
        "squareFeetRange": "5000+ sq ft",
        "yearBuiltRange": "2021+",
        "parking": "Available",
        "garden": "Yes",
        "flooring": "Marble",
        "view": "Sea",
        "airConditioning": "Available",
        "heating": "Central",
        "pool": "Available",
        "balcony": "Available",
        "roof": "Flat",
        "security": "Available",
        "schools": "Yes",
        "internet": "Available",
        "gym": "Available",
        "storage": "Available",
        "shopping": "Close",
        "hospital": "Yes",
        "park": "Yes"
    },
    {
        "imgUrl": "https://via.placeholder.com/250",
        "title": "Charming Cottage in Nassau",
        "price": "$350,000",
        "description": "A cozy 2-bedroom cottage located in a quiet neighborhood of Nassau, with a lovely garden and close to the beach.",
        "address": "Nassau, Bahamas",
        "bedrooms": 2,
        "bathrooms": 1,
        "squareFeet": "1200",
        "yearBuilt": "2015",
        "propertyType": "House",
        "country": "Bahamas",
        "city": "Nassau",
        "priceRange": "300,000 - 500,000",
        "squareFeetRange": "1000 - 2000 sq ft",
        "yearBuiltRange": "2011 - 2020",
        "parking": "Available",
        "garden": "Yes",
        "flooring": "Wood",
        "view": "Park",
        "airConditioning": "Available",
        "heating": "Individual",
        "pool": "Not Available",
        "balcony": "Not Available",
        "roof": "Sloped",
        "security": "Not Available",
        "schools": "No",
        "internet": "Available",
        "gym": "Not Available",
        "storage": "Not Available",
        "shopping": "Close",
        "hospital": "No",
        "park": "No"
    },
    {
        "imgUrl": "https://via.placeholder.com/250",
        "title": "Charming Apartment in Buenos Aires",
        "price": "$180,000",
        "description": "A beautiful 1-bedroom apartment located in the heart of Buenos Aires, ideal for young professionals or students.",
        "address": "Buenos Aires, Argentina",
        "bedrooms": 1,
        "bathrooms": 1,
        "squareFeet": "800",
        "yearBuilt": "2005",
        "propertyType": "Apartment",
        "country": "Argentina",
        "city": "Buenos Aires",
        "priceRange": "Up to 100,000",
        "squareFeetRange": "Up to 1000 sq ft",
        "yearBuiltRange": "Before 2000",
        "parking": "Not Available",
        "garden": "No",
        "flooring": "Tile",
        "view": "City",
        "airConditioning": "Available",
        "heating": "Individual",
        "pool": "Not Available",
        "balcony": "Not Available",
        "roof": "Sloped",
        "security": "Not Available",
        "schools": "Yes",
        "internet": "Available",
        "gym": "Not Available",
        "storage": "Not Available",
        "shopping": "Close",
        "hospital": "Yes",
        "park": "Yes"
    },
    {
        "imgUrl": "https://via.placeholder.com/250",
        "title": "Spacious House in Buenos Aires Suburbs",
        "price": "$750,000",
        "description": "A spacious 4-bedroom house with a large garden located just outside Buenos Aires, offering a peaceful suburban lifestyle.",
        "address": "Buenos Aires Suburbs, Argentina",
        "bedrooms": 4,
        "bathrooms": 3,
        "squareFeet": "3500",
        "yearBuilt": "2017",
        "propertyType": "House",
        "country": "Argentina",
        "city": "Buenos Aires Suburbs",
        "priceRange": "500,000 - 1,000,000",
        "squareFeetRange": "3000 - 5000 sq ft",
        "yearBuiltRange": "2011 - 2020",
        "parking": "Available",
        "garden": "Yes",
        "flooring": "Wood",
        "view": "Park",
        "airConditioning": "Available",
        "heating": "Central",
        "pool": "Available",
        "balcony": "Available",
        "roof": "Flat",
        "security": "Available",
        "schools": "Yes",
        "internet": "Available",
        "gym": "Available",
        "storage": "Available",
        "shopping": "Far",
        "hospital": "Yes",
        "park": "Yes"
    },
    {
        "imgUrl": "https://via.placeholder.com/250",
        "title": "Luxury Villa in Yerevan",
        "price": "$2,500,000",
        "description": "A stunning 6-bedroom villa in the capital city, featuring luxurious finishes and breathtaking views of Mount Ararat.",
        "address": "Yerevan, Armenia",
        "bedrooms": 6,
        "bathrooms": 5,
        "squareFeet": "8000",
        "yearBuilt": "2021",
        "propertyType": "Villa",
        "country": "Armenia",
        "city": "Yerevan",
        "priceRange": "2,000,000+",
        "squareFeetRange": "5000+ sq ft",
        "yearBuiltRange": "2021+",
        "parking": "Available",
        "garden": "Yes",
        "flooring": "Marble",
        "view": "Mountain",
        "airConditioning": "Available",
        "heating": "Central",
        "pool": "Available",
        "balcony": "Available",
        "roof": "Flat",
        "security": "Available",
        "schools": "Yes",
        "internet": "Available",
        "gym": "Available",
        "storage": "Available",
        "shopping": "Close",
        "hospital": "Yes",
        "park": "Yes"
    },
    {
        "imgUrl": "https://via.placeholder.com/250",
        "title": "Cozy Condo in Yerevan",
        "price": "$350,000",
        "description": "A cozy 2-bedroom condo with city views in central Yerevan, perfect for urban living.",
        "address": "Yerevan, Armenia",
        "bedrooms": 2,
        "bathrooms": 2,
        "squareFeet": "1000",
        "yearBuilt": "2015",
        "propertyType": "Condo",
        "country": "Armenia",
        "city": "Yerevan",
        "priceRange": "300,000 - 500,000",
        "squareFeetRange": "1000 - 2000 sq ft",
        "yearBuiltRange": "2011 - 2020",
        "parking": "Not Available",
        "garden": "No",
        "flooring": "Wood",
        "view": "City",
        "airConditioning": "Available",
        "heating": "Individual",
        "pool": "Not Available",
        "balcony": "Available",
        "roof": "Sloped",
        "security": "Not Available",
        "schools": "Yes",
        "internet": "Available",
        "gym": "Not Available",
        "storage": "Not Available",
        "shopping": "Close",
        "hospital": "Yes",
        "park": "No"
    },
    {
        "imgUrl": "https://via.placeholder.com/250",
        "title": "Beach House in Gold Coast",
        "price": "$1,500,000",
        "description": "A modern 4-bedroom beach house in the picturesque Gold Coast, with stunning ocean views and private access to the beach.",
        "address": "Gold Coast, Australia",
        "bedrooms": 4,
        "bathrooms": 4,
        "squareFeet": "6000",
        "yearBuilt": "2020",
        "propertyType": "House",
        "country": "Australia",
        "city": "Gold Coast",
        "priceRange": "1,000,000 - 2,000,000",
        "squareFeetRange": "5000+ sq ft",
        "yearBuiltRange": "2021+",
        "parking": "Available",
        "garden": "Yes",
        "flooring": "Marble",
        "view": "Sea",
        "airConditioning": "Available",
        "heating": "Central",
        "pool": "Available",
        "balcony": "Available",
        "roof": "Flat",
        "security": "Available",
        "schools": "Yes",
        "internet": "Available",
        "gym": "Available",
        "storage": "Available",
        "shopping": "Close",
        "hospital": "Yes",
        "park": "Yes"
    },
    {
        "imgUrl": "https://via.placeholder.com/250",
        "title": "Mountain Retreat in Melbourne",
        "price": "$2,000,000",
        "description": "A serene 5-bedroom mountain retreat with panoramic views of the Australian Alps, offering the perfect escape from city life.",
        "address": "Melbourne, Australia",
        "bedrooms": 5,
        "bathrooms": 5,
        "squareFeet": "7500",
        "yearBuilt": "2021",
        "propertyType": "Villa",
        "country": "Australia",
        "city": "Melbourne",
        "priceRange": "1,000,000 - 2,000,000",
        "squareFeetRange": "5000+ sq ft",
        "yearBuiltRange": "2021+",
        "parking": "Available",
        "garden": "Yes",
        "flooring": "Wood",
        "view": "Mountain",
        "airConditioning": "Available",
        "heating": "Central",
        "pool": "Available",
        "balcony": "Available",
        "roof": "Flat",
        "security": "Available",
        "schools": "Yes",
        "internet": "Available",
        "gym": "Available",
        "storage": "Available",
        "shopping": "Far",
        "hospital": "Yes",
        "park": "Yes"
    },
    {
        "imgUrl": "https://via.placeholder.com/250",
        "title": "Modern Condo in Brussels",
        "price": "$450,000",
        "description": "A stylish 2-bedroom condo located in central Brussels, close to public transport and shopping areas.",
        "address": "Brussels, Belgium",
        "bedrooms": 2,
        "bathrooms": 1,
        "squareFeet": "1200",
        "yearBuilt": "2018",
        "propertyType": "Condo",
        "country": "Belgium",
        "city": "Brussels",
        "priceRange": "300,000 - 500,000",
        "squareFeetRange": "1000 - 2000 sq ft",
        "yearBuiltRange": "2011 - 2020",
        "parking": "Not Available",
        "garden": "No",
        "flooring": "Tile",
        "view": "City",
        "airConditioning": "Available",
        "heating": "Individual",
        "pool": "Not Available",
        "balcony": "Available",
        "roof": "Sloped",
        "security": "Not Available",
        "schools": "Yes",
        "internet": "Available",
        "gym": "Not Available",
        "storage": "Not Available",
        "shopping": "Close",
        "hospital": "Yes",
        "park": "No"
    },
    {
        "imgUrl": "https://via.placeholder.com/250",
        "title": "Luxury Villa in Antwerp",
        "price": "$3,000,000",
        "description": "A stunning 5-bedroom villa with modern amenities and a beautiful garden, located in the upscale area of Antwerp.",
        "address": "Antwerp, Belgium",
        "bedrooms": 5,
        "bathrooms": 4,
        "squareFeet": "6500",
        "yearBuilt": "2020",
        "propertyType": "Villa",
        "country": "Belgium",
        "city": "Antwerp",
        "priceRange": "2,000,000+",
        "squareFeetRange": "5000+ sq ft",
        "yearBuiltRange": "2021+",
        "parking": "Available",
        "garden": "Yes",
        "flooring": "Wood",
        "view": "Park",
        "airConditioning": "Available",
        "heating": "Central",
        "pool": "Available",
        "balcony": "Available",
        "roof": "Flat",
        "security": "Available",
        "schools": "Yes",
        "internet": "Available",
        "gym": "Available",
        "storage": "Available",
        "shopping": "Far",
        "hospital": "Yes",
        "park": "Yes"
    },
    {
        "imgUrl": "https://via.placeholder.com/250",
        "title": "Beachfront House in Nassau",
        "price": "$2,000,000",
        "description": "A luxurious 4-bedroom beachfront house in Nassau, Bahamas, with direct access to the beach and ocean views.",
        "address": "Nassau, Bahamas",
        "bedrooms": 4,
        "bathrooms": 3,
        "squareFeet": "5000",
        "yearBuilt": "2015",
        "propertyType": "House",
        "country": "Bahamas",
        "city": "Nassau",
        "priceRange": "1,000,000 - 2,000,000",
        "squareFeetRange": "3000 - 5000 sq ft",
        "yearBuiltRange": "2011 - 2020",
        "parking": "Available",
        "garden": "Yes",
        "flooring": "Marble",
        "view": "Sea",
        "airConditioning": "Available",
        "heating": "Central",
        "pool": "Available",
        "balcony": "Available",
        "roof": "Flat",
        "security": "Available",
        "schools": "Yes",
        "internet": "Available",
        "gym": "Not Available",
        "storage": "Available",
        "shopping": "Close",
        "hospital": "Yes",
        "park": "No"
    },
    {
        "imgUrl": "https://via.placeholder.com/250",
        "title": "Charming Cottage in Grand Bahama",
        "price": "$450,000",
        "description": "A 2-bedroom cottage with a beautiful garden and close proximity to the beach, perfect for a cozy family getaway.",
        "address": "Grand Bahama, Bahamas",
        "bedrooms": 2,
        "bathrooms": 1,
        "squareFeet": "1200",
        "yearBuilt": "2010",
        "propertyType": "House",
        "country": "Bahamas",
        "city": "Grand Bahama",
        "priceRange": "Up to 100,000",
        "squareFeetRange": "Up to 1000 sq ft",
        "yearBuiltRange": "Before 2000",
        "parking": "Not Available",
        "garden": "Yes",
        "flooring": "Wood",
        "view": "Park",
        "airConditioning": "Not Available",
        "heating": "Individual",
        "pool": "Not Available",
        "balcony": "Not Available",
        "roof": "Sloped",
        "security": "Not Available",
        "schools": "Yes",
        "internet": "Available",
        "gym": "Not Available",
        "storage": "Not Available",
        "shopping": "Close",
        "hospital": "Yes",
        "park": "Yes"
    },
    {
        "imgUrl": "https://via.placeholder.com/250",
        "title": "Luxury Penthouse in Dubai",
        "price": "$5,000,000",
        "description": "A high-end 4-bedroom penthouse with breathtaking views of the Burj Khalifa, featuring a private pool and spacious balcony.",
        "address": "Dubai, United Arab Emirates",
        "bedrooms": 4,
        "bathrooms": 5,
        "squareFeet": "8000",
        "yearBuilt": "2022",
        "propertyType": "Condo",
        "country": "United Arab Emirates",
        "city": "Dubai",
        "priceRange": "2,000,000+",
        "squareFeetRange": "5000+ sq ft",
        "yearBuiltRange": "2021+",
        "parking": "Available",
        "garden": "Yes",
        "flooring": "Wood",
        "view": "City",
        "airConditioning": "Available",
        "heating": "Central",
        "pool": "Available",
        "balcony": "Available",
        "roof": "Flat",
        "security": "Available",
        "schools": "Yes",
        "internet": "Available",
        "gym": "Available",
        "storage": "Available",
        "shopping": "Close",
        "hospital": "Yes",
        "park": "No"
    },
    {
        "imgUrl": "https://via.placeholder.com/250",
        "title": "Modern Villa in Dubai Marina",
        "price": "$3,500,000",
        "description": "A sleek, contemporary 5-bedroom villa with luxury finishes, located in the sought-after Dubai Marina area with private beach access.",
        "address": "Dubai Marina, United Arab Emirates",
        "bedrooms": 5,
        "bathrooms": 6,
        "squareFeet": "7000",
        "yearBuilt": "2021",
        "propertyType": "Villa",
        "country": "United Arab Emirates",
        "city": "Dubai Marina",
        "priceRange": "2,000,000+",
        "squareFeetRange": "5000+ sq ft",
        "yearBuiltRange": "2021+",
        "parking": "Available",
        "garden": "Yes",
        "flooring": "Marble",
        "view": "Sea",
        "airConditioning": "Available",
        "heating": "Central",
        "pool": "Available",
        "balcony": "Available",
        "roof": "Flat",
        "security": "Available",
        "schools": "Yes",
        "internet": "Available",
        "gym": "Available",
        "storage": "Available",
        "shopping": "Close",
        "hospital": "Yes",
        "park": "Yes"
    },
    {
        "imgUrl": "https://via.placeholder.com/250",
        "title": "Charming Cottage in Buenos Aires",
        "price": "$350,000",
        "description": "A cozy 3-bedroom cottage in the heart of Buenos Aires, offering a peaceful retreat with easy access to city amenities.",
        "address": "Buenos Aires, Argentina",
        "bedrooms": 3,
        "bathrooms": 2,
        "squareFeet": "2500",
        "yearBuilt": "2015",
        "propertyType": "House",
        "country": "Argentina",
        "city": "Buenos Aires",
        "priceRange": "300,000 - 500,000",
        "squareFeetRange": "2000 - 3000 sq ft",
        "yearBuiltRange": "2011 - 2020",
        "parking": "Available",
        "garden": "Yes",
        "flooring": "Wood",
        "view": "Park",
        "airConditioning": "Available",
        "heating": "Individual",
        "pool": "Not Available",
        "balcony": "Not Available",
        "roof": "Sloped",
        "security": "Not Available",
        "schools": "Yes",
        "internet": "Available",
        "gym": "Not Available",
        "storage": "Not Available",
        "shopping": "Close",
        "hospital": "Yes",
        "park": "Yes"
    },
    {
        "imgUrl": "https://via.placeholder.com/250",
        "title": "Luxury Apartment in Buenos Aires",
        "price": "$850,000",
        "description": "An elegant 2-bedroom apartment with modern finishes and a panoramic city view, situated in the best neighborhood of Buenos Aires.",
        "address": "Buenos Aires, Argentina",
        "bedrooms": 2,
        "bathrooms": 2,
        "squareFeet": "1500",
        "yearBuilt": "2020",
        "propertyType": "Apartment",
        "country": "Argentina",
        "city": "Buenos Aires",
        "priceRange": "500,000 - 1,000,000",
        "squareFeetRange": "1000 - 2000 sq ft",
        "yearBuiltRange": "2021+",
        "parking": "Not Available",
        "garden": "No",
        "flooring": "Tile",
        "view": "City",
        "airConditioning": "Available",
        "heating": "Central",
        "pool": "Not Available",
        "balcony": "Available",
        "roof": "Flat",
        "security": "Available",
        "schools": "Yes",
        "internet": "Available",
        "gym": "Available",
        "storage": "Not Available",
        "shopping": "Close",
        "hospital": "Yes",
        "park": "No"
    },
    {
        "imgUrl": "https://via.placeholder.com/250",
        "title": "Mountain Retreat in Yerevan",
        "price": "$550,000",
        "description": "A peaceful 4-bedroom house nestled in the mountains of Armenia with beautiful views and modern amenities.",
        "address": "Yerevan, Armenia",
        "bedrooms": 4,
        "bathrooms": 3,
        "squareFeet": "3000",
        "yearBuilt": "2018",
        "propertyType": "House",
        "country": "Armenia",
        "city": "Yerevan",
        "priceRange": "300,000 - 500,000",
        "squareFeetRange": "3000 - 5000 sq ft",
        "yearBuiltRange": "2011 - 2020",
        "parking": "Available",
        "garden": "Yes",
        "flooring": "Wood",
        "view": "Mountain",
        "airConditioning": "Available",
        "heating": "Individual",
        "pool": "Not Available",
        "balcony": "Available",
        "roof": "Sloped",
        "security": "Not Available",
        "schools": "Yes",
        "internet": "Available",
        "gym": "Not Available",
        "storage": "Available",
        "shopping": "Far",
        "hospital": "Yes",
        "park": "Yes"
    },
    {
        "imgUrl": "https://via.placeholder.com/250",
        "title": "Beach House in Sydney",
        "price": "$2,500,000",
        "description": "A luxurious 5-bedroom beach house with panoramic views of the ocean, located in the prime area of Sydney.",
        "address": "Sydney, Australia",
        "bedrooms": 5,
        "bathrooms": 4,
        "squareFeet": "6000",
        "yearBuilt": "2020",
        "propertyType": "House",
        "country": "Australia",
        "city": "Sydney",
        "priceRange": "2,000,000+",
        "squareFeetRange": "5000+ sq ft",
        "yearBuiltRange": "2021+",
        "parking": "Available",
        "garden": "Yes",
        "flooring": "Wood",
        "view": "Sea",
        "airConditioning": "Available",
        "heating": "Central",
        "pool": "Available",
        "balcony": "Available",
        "roof": "Flat",
        "security": "Available",
        "schools": "Yes",
        "internet": "Available",
        "gym": "Available",
        "storage": "Available",
        "shopping": "Close",
        "hospital": "Yes",
        "park": "Yes"
    },
    {
        "imgUrl": "https://via.placeholder.com/250",
        "title": "Modern Condo in Melbourne",
        "price": "$750,000",
        "description": "A stylish 3-bedroom condo located in the heart of Melbourne, with convenient access to public transport and shopping.",
        "address": "Melbourne, Australia",
        "bedrooms": 3,
        "bathrooms": 2,
        "squareFeet": "1800",
        "yearBuilt": "2021",
        "propertyType": "Condo",
        "country": "Australia",
        "city": "Melbourne",
        "priceRange": "500,000 - 1,000,000",
        "squareFeetRange": "1000 - 2000 sq ft",
        "yearBuiltRange": "2021+",
        "parking": "Available",
        "garden": "No",
        "flooring": "Tile",
        "view": "City",
        "airConditioning": "Available",
        "heating": "Individual",
        "pool": "Not Available",
        "balcony": "Not Available",
        "roof": "Flat",
        "security": "Available",
        "schools": "Yes",
        "internet": "Available",
        "gym": "Not Available",
        "storage": "Not Available",
        "shopping": "Close",
        "hospital": "Yes",
        "park": "No"
    },
    {
        "imgUrl": "https://via.placeholder.com/250",
        "title": "Elegant Townhouse in Vienna",
        "price": "$1,200,000",
        "description": "A beautiful 3-bedroom townhouse with classic design and modern touches, located in Vienna's historic center.",
        "address": "Vienna, Austria",
        "bedrooms": 3,
        "bathrooms": 2,
        "squareFeet": "2500",
        "yearBuilt": "2017",
        "propertyType": "Townhouse",
        "country": "Austria",
        "city": "Vienna",
        "priceRange": "1,000,000 - 2,000,000",
        "squareFeetRange": "2000 - 3000 sq ft",
        "yearBuiltRange": "2011 - 2020",
        "parking": "Available",
        "garden": "Yes",
        "flooring": "Wood",
        "view": "Park",
        "airConditioning": "Available",
        "heating": "Central",
        "pool": "Not Available",
        "balcony": "Available",
        "roof": "Sloped",
        "security": "Available",
        "schools": "Yes",
        "internet": "Available",
        "gym": "Not Available",
        "storage": "Available",
        "shopping": "Close",
        "hospital": "Yes",
        "park": "Yes"
    },
    {
        "imgUrl": "https://via.placeholder.com/250",
        "title": "Spacious Villa in Baku",
        "price": "$1,800,000",
        "description": "A large 6-bedroom villa in the prestigious area of Baku, featuring spacious interiors and luxurious amenities.",
        "address": "Baku, Azerbaijan",
        "bedrooms": 6,
        "bathrooms": 5,
        "squareFeet": "8000",
        "yearBuilt": "2021",
        "propertyType": "Villa",
        "country": "Azerbaijan",
        "city": "Baku",
        "priceRange": "1,000,000 - 2,000,000",
        "squareFeetRange": "5000+ sq ft",
        "yearBuiltRange": "2021+",
        "parking": "Available",
        "garden": "Yes",
        "flooring": "Marble",
        "view": "City",
        "airConditioning": "Available",
        "heating": "Central",
        "pool": "Available",
        "balcony": "Available",
        "roof": "Flat",
        "security": "Available",
        "schools": "Yes",
        "internet": "Available",
        "gym": "Available",
        "storage": "Available",
        "shopping": "Close",
        "hospital": "Yes",
        "park": "No"
    },
    {
        "imgUrl": "https://via.placeholder.com/250",
        "title": "Penthouse in Baku City Center",
        "price": "$2,200,000",
        "description": "An exclusive 4-bedroom penthouse with breathtaking views of the Baku skyline, located in the heart of the city.",
        "address": "Baku, Azerbaijan",
        "bedrooms": 4,
        "bathrooms": 3,
        "squareFeet": "6000",
        "yearBuilt": "2019",
        "propertyType": "Condo",
        "country": "Azerbaijan",
        "city": "Baku",
        "priceRange": "2,000,000+",
        "squareFeetRange": "5000+ sq ft",
        "yearBuiltRange": "2011 - 2020",
        "parking": "Available",
        "garden": "No",
        "flooring": "Tile",
        "view": "City",
        "airConditioning": "Available",
        "heating": "Central",
        "pool": "Not Available",
        "balcony": "Available",
        "roof": "Flat",
        "security": "Available",
        "schools": "Yes",
        "internet": "Available",
        "gym": "Available",
        "storage": "Available",
        "shopping": "Close",
        "hospital": "Yes",
        "park": "No"
    },
    {
        "imgUrl": "https://via.placeholder.com/250",
        "title": "Elegant Beachfront House in Nassau",
        "price": "$3,800,000",
        "description": "A beautiful 4-bedroom beachfront house with private access to the beach, located in a prestigious area of Nassau.",
        "address": "Nassau, Bahamas",
        "bedrooms": 4,
        "bathrooms": 3,
        "squareFeet": "7000",
        "yearBuilt": "2022",
        "propertyType": "House",
        "country": "Bahamas",
        "city": "Nassau",
        "priceRange": "2,000,000+",
        "squareFeetRange": "5000+ sq ft",
        "yearBuiltRange": "2021+",
        "parking": "Available",
        "garden": "Yes",
        "flooring": "Marble",
        "view": "Sea",
        "airConditioning": "Available",
        "heating": "Central",
        "pool": "Available",
        "balcony": "Available",
        "roof": "Flat",
        "security": "Available",
        "schools": "Yes",
        "internet": "Available",
        "gym": "Available",
        "storage": "Available",
        "shopping": "Close",
        "hospital": "Yes",
        "park": "No"
    },
    {
        "imgUrl": "https://via.placeholder.com/250",
        "title": "Luxury Villa in La Paz",
        "price": "$1,500,000",
        "description": "A stunning 5-bedroom villa with panoramic views of the city and mountains, offering a perfect blend of luxury and comfort.",
        "address": "La Paz, Bolivia",
        "bedrooms": 5,
        "bathrooms": 4,
        "squareFeet": "5000",
        "yearBuilt": "2019",
        "propertyType": "Villa",
        "country": "Bolivia",
        "city": "La Paz",
        "priceRange": "1,000,000 - 2,000,000",
        "squareFeetRange": "5000+ sq ft",
        "yearBuiltRange": "2011 - 2020",
        "parking": "Available",
        "garden": "Yes",
        "flooring": "Wood",
        "view": "Mountain",
        "airConditioning": "Available",
        "heating": "Central",
        "pool": "Available",
        "balcony": "Available",
        "roof": "Flat",
        "security": "Available",
        "schools": "Yes",
        "internet": "Available",
        "gym": "Available",
        "storage": "Available",
        "shopping": "Close",
        "hospital": "Yes",
        "park": "Yes"
    },
    {
        "imgUrl": "https://via.placeholder.com/250",
        "title": "Modern Apartment in Sarajevo",
        "price": "$450,000",
        "description": "A contemporary 3-bedroom apartment located in the heart of Sarajevo, close to shops and restaurants.",
        "address": "Sarajevo, Bosnia and Herzegovina",
        "bedrooms": 3,
        "bathrooms": 2,
        "squareFeet": "1500",
        "yearBuilt": "2020",
        "propertyType": "Apartment",
        "country": "Bosnia and Herzegovina",
        "city": "Sarajevo",
        "priceRange": "300,000 - 500,000",
        "squareFeetRange": "1000 - 2000 sq ft",
        "yearBuiltRange": "2021+",
        "parking": "Available",
        "garden": "No",
        "flooring": "Tile",
        "view": "City",
        "airConditioning": "Available",
        "heating": "Individual",
        "pool": "Not Available",
        "balcony": "Not Available",
        "roof": "Flat",
        "security": "Not Available",
        "schools": "Yes",
        "internet": "Available",
        "gym": "Not Available",
        "storage": "Not Available",
        "shopping": "Close",
        "hospital": "Yes",
        "park": "No"
    },
    {
        "imgUrl": "https://via.placeholder.com/250",
        "title": "Cozy Cottage in Gaborone",
        "price": "$280,000",
        "description": "A charming 2-bedroom cottage with a peaceful garden in the tranquil suburbs of Gaborone, Botswana.",
        "address": "Gaborone, Botswana",
        "bedrooms": 2,
        "bathrooms": 1,
        "squareFeet": "1200",
        "yearBuilt": "2015",
        "propertyType": "Cottage",
        "country": "Botswana",
        "city": "Gaborone",
        "priceRange": "200,000 - 300,000",
        "squareFeetRange": "Up to 1000 sq ft",
        "yearBuiltRange": "2011 - 2020",
        "parking": "Available",
        "garden": "Yes",
        "flooring": "Wood",
        "view": "Park",
        "airConditioning": "Not Available",
        "heating": "Individual",
        "pool": "Not Available",
        "balcony": "Not Available",
        "roof": "Sloped",
        "security": "Not Available",
        "schools": "Yes",
        "internet": "Available",
        "gym": "Not Available",
        "storage": "Not Available",
        "shopping": "Far",
        "hospital": "Yes",
        "park": "Yes"
    },
    {
        "imgUrl": "https://via.placeholder.com/250",
        "title": "Elegant Mansion in São Paulo",
        "price": "$4,500,000",
        "description": "A luxurious 7-bedroom mansion with state-of-the-art amenities, a grand garden, and a private pool in São Paulo.",
        "address": "São Paulo, Brazil",
        "bedrooms": 7,
        "bathrooms": 6,
        "squareFeet": "9000",
        "yearBuilt": "2021",
        "propertyType": "Mansion",
        "country": "Brazil",
        "city": "São Paulo",
        "priceRange": "2,000,000+",
        "squareFeetRange": "5000+ sq ft",
        "yearBuiltRange": "2021+",
        "parking": "Available",
        "garden": "Yes",
        "flooring": "Marble",
        "view": "City",
        "airConditioning": "Available",
        "heating": "Central",
        "pool": "Available",
        "balcony": "Available",
        "roof": "Flat",
        "security": "Available",
        "schools": "Yes",
        "internet": "Available",
        "gym": "Available",
        "storage": "Available",
        "shopping": "Close",
        "hospital": "Yes",
        "park": "Yes"
    },
    {
        "imgUrl": "https://via.placeholder.com/250",
        "title": "Mountain View Villa in Cusco",
        "price": "$650,000",
        "description": "A beautiful 4-bedroom villa with breathtaking views of the Andes, offering a quiet retreat in the historic city of Cusco.",
        "address": "Cusco, Peru",
        "bedrooms": 4,
        "bathrooms": 3,
        "squareFeet": "3500",
        "yearBuilt": "2018",
        "propertyType": "Villa",
        "country": "Peru",
        "city": "Cusco",
        "priceRange": "500,000 - 1,000,000",
        "squareFeetRange": "3000 - 5000 sq ft",
        "yearBuiltRange": "2011 - 2020",
        "parking": "Available",
        "garden": "Yes",
        "flooring": "Wood",
        "view": "Mountain",
        "airConditioning": "Not Available",
        "heating": "Individual",
        "pool": "Not Available",
        "balcony": "Available",
        "roof": "Sloped",
        "security": "Not Available",
        "schools": "Yes",
        "internet": "Available",
        "gym": "Not Available",
        "storage": "Available",
        "shopping": "Far",
        "hospital": "Yes",
        "park": "Yes"
    },
    {
        "imgUrl": "https://via.placeholder.com/250",
        "title": "Cozy House in Montevideo",
        "price": "$450,000",
        "description": "A quaint 3-bedroom house in a quiet neighborhood of Montevideo, with a lovely garden and close to shops.",
        "address": "Montevideo, Uruguay",
        "bedrooms": 3,
        "bathrooms": 2,
        "squareFeet": "1800",
        "yearBuilt": "2016",
        "propertyType": "House",
        "country": "Uruguay",
        "city": "Montevideo",
        "priceRange": "300,000 - 500,000",
        "squareFeetRange": "1000 - 2000 sq ft",
        "yearBuiltRange": "2011 - 2020",
        "parking": "Available",
        "garden": "Yes",
        "flooring": "Wood",
        "view": "Park",
        "airConditioning": "Available",
        "heating": "Individual",
        "pool": "Not Available",
        "balcony": "Not Available",
        "roof": "Flat",
        "security": "Not Available",
        "schools": "Yes",
        "internet": "Available",
        "gym": "Not Available",
        "storage": "Not Available",
        "shopping": "Close",
        "hospital": "Yes",
        "park": "Yes"
    },
    {
        "imgUrl": "https://via.placeholder.com/250",
        "title": "Beachfront Condo in Rio de Janeiro",
        "price": "$1,200,000",
        "description": "A stunning 2-bedroom beachfront condo with modern amenities and panoramic ocean views, in the lively city of Rio.",
        "address": "Rio de Janeiro, Brazil",
        "bedrooms": 2,
        "bathrooms": 2,
        "squareFeet": "1500",
        "yearBuilt": "2021",
        "propertyType": "Condo",
        "country": "Brazil",
        "city": "Rio de Janeiro",
        "priceRange": "1,000,000 - 2,000,000",
        "squareFeetRange": "1000 - 2000 sq ft",
        "yearBuiltRange": "2021+",
        "parking": "Available",
        "garden": "No",
        "flooring": "Tile",
        "view": "Sea",
        "airConditioning": "Available",
        "heating": "Individual",
        "pool": "Not Available",
        "balcony": "Available",
        "roof": "Flat",
        "security": "Available",
        "schools": "Yes",
        "internet": "Available",
        "gym": "Available",
        "storage": "Not Available",
        "shopping": "Close",
        "hospital": "Yes",
        "park": "No"
    },
    {
        "imgUrl": "https://via.placeholder.com/250",
        "title": "Luxury Mansion in Medellín",
        "price": "$3,000,000",
        "description": "A luxurious 6-bedroom mansion located in the hills of Medellín, offering privacy, stunning views, and modern amenities.",
        "address": "Medellín, Colombia",
        "bedrooms": 6,
        "bathrooms": 5,
        "squareFeet": "8000",
        "yearBuilt": "2021",
        "propertyType": "Mansion",
        "country": "Colombia",
        "city": "Medellín",
        "priceRange": "2,000,000+",
        "squareFeetRange": "5000+ sq ft",
        "yearBuiltRange": "2021+",
        "parking": "Available",
        "garden": "Yes",
        "flooring": "Marble",
        "view": "Mountain",
        "airConditioning": "Available",
        "heating": "Central",
        "pool": "Available",
        "balcony": "Available",
        "roof": "Flat",
        "security": "Available",
        "schools": "Yes",
        "internet": "Available",
        "gym": "Available",
        "storage": "Available",
        "shopping": "Close",
        "hospital": "Yes",
        "park": "Yes"
    },
    {
        "imgUrl": "https://via.placeholder.com/250",
        "title": "Cozy Loft in Havana",
        "price": "$350,000",
        "description": "A charming 2-bedroom loft in the heart of Havana, featuring traditional Cuban design and modern amenities.",
        "address": "Havana, Cuba",
        "bedrooms": 2,
        "bathrooms": 1,
        "squareFeet": "1000",
        "yearBuilt": "2017",
        "propertyType": "Loft",
        "country": "Cuba",
        "city": "Havana",
        "priceRange": "200,000 - 300,000",
        "squareFeetRange": "Up to 1000 sq ft",
        "yearBuiltRange": "2011 - 2020",
        "parking": "Not Available",
        "garden": "No",
        "flooring": "Tile",
        "view": "City",
        "airConditioning": "Available",
        "heating": "Not Available",
        "pool": "Not Available",
        "balcony": "Not Available",
        "roof": "Flat",
        "security": "Not Available",
        "schools": "Yes",
        "internet": "Not Available",
        "gym": "Not Available",
        "storage": "Not Available",
        "shopping": "Close",
        "hospital": "Yes",
        "park": "No"
    },
    {
        "imgUrl": "https://via.placeholder.com/250",
        "title": "Modern Apartment in New York City",
        "price": "$1,800,000",
        "description": "A contemporary 2-bedroom apartment with stunning views of the city skyline and luxurious amenities in the heart of Manhattan.",
        "address": "New York City, United States",
        "bedrooms": 2,
        "bathrooms": 2,
        "squareFeet": "1600",
        "yearBuilt": "2022",
        "propertyType": "Apartment",
        "country": "United States",
        "city": "New York City",
        "priceRange": "1,000,000 - 2,000,000",
        "squareFeetRange": "1000 - 2000 sq ft",
        "yearBuiltRange": "2021+",
        "parking": "Available",
        "garden": "No",
        "flooring": "Wood",
        "view": "City",
        "airConditioning": "Available",
        "heating": "Central",
        "pool": "Not Available",
        "balcony": "Available",
        "roof": "Flat",
        "security": "Available",
        "schools": "Yes",
        "internet": "Available",
        "gym": "Available",
        "storage": "Available",
        "shopping": "Close",
        "hospital": "Yes",
        "park": "Yes"
    },
    {
        "imgUrl": "https://via.placeholder.com/250",
        "title": "Beach House in Bali",
        "price": "$2,500,000",
        "description": "An exquisite 4-bedroom beachfront house offering panoramic views of the ocean and surrounded by lush tropical gardens.",
        "address": "Bali, Indonesia",
        "bedrooms": 4,
        "bathrooms": 3,
        "squareFeet": "4000",
        "yearBuilt": "2019",
        "propertyType": "House",
        "country": "Indonesia",
        "city": "Bali",
        "priceRange": "2,000,000+",
        "squareFeetRange": "3000 - 5000 sq ft",
        "yearBuiltRange": "2011 - 2020",
        "parking": "Available",
        "garden": "Yes",
        "flooring": "Marble",
        "view": "Sea",
        "airConditioning": "Available",
        "heating": "Individual",
        "pool": "Available",
        "balcony": "Available",
        "roof": "Sloped",
        "security": "Available",
        "schools": "Yes",
        "internet": "Available",
        "gym": "Available",
        "storage": "Available",
        "shopping": "Close",
        "hospital": "Yes",
        "park": "No"
    },
    {
        "imgUrl": "https://via.placeholder.com/250",
        "title": "Charming Cottage in Edinburgh",
        "price": "$750,000",
        "description": "A quaint 3-bedroom cottage located in the picturesque countryside near Edinburgh, offering a peaceful retreat.",
        "address": "Edinburgh, United Kingdom",
        "bedrooms": 3,
        "bathrooms": 2,
        "squareFeet": "1800",
        "yearBuilt": "2015",
        "propertyType": "Cottage",
        "country": "United Kingdom",
        "city": "Edinburgh",
        "priceRange": "500,000 - 1,000,000",
        "squareFeetRange": "1000 - 2000 sq ft",
        "yearBuiltRange": "2011 - 2020",
        "parking": "Available",
        "garden": "Yes",
        "flooring": "Wood",
        "view": "Park",
        "airConditioning": "Not Available",
        "heating": "Central",
        "pool": "Not Available",
        "balcony": "Not Available",
        "roof": "Sloped",
        "security": "Not Available",
        "schools": "Yes",
        "internet": "Available",
        "gym": "Not Available",
        "storage": "Available",
        "shopping": "Far",
        "hospital": "Yes",
        "park": "Yes"
    },
    {
        "imgUrl": "https://via.placeholder.com/250",
        "title": "Luxury Condo in Paris",
        "price": "$3,000,000",
        "description": "A beautifully designed 3-bedroom luxury condo located near the Eiffel Tower, with high-end finishes and stunning city views.",
        "address": "Paris, France",
        "bedrooms": 3,
        "bathrooms": 2,
        "squareFeet": "2200",
        "yearBuilt": "2021",
        "propertyType": "Condo",
        "country": "France",
        "city": "Paris",
        "priceRange": "2,000,000+",
        "squareFeetRange": "2000 - 3000 sq ft",
        "yearBuiltRange": "2021+",
        "parking": "Available",
        "garden": "No",
        "flooring": "Wood",
        "view": "City",
        "airConditioning": "Available",
        "heating": "Central",
        "pool": "Not Available",
        "balcony": "Available",
        "roof": "Flat",
        "security": "Available",
        "schools": "Yes",
        "internet": "Available",
        "gym": "Available",
        "storage": "Available",
        "shopping": "Close",
        "hospital": "Yes",
        "park": "Yes"
    },
    {
        "imgUrl": "https://via.placeholder.com/250",
        "title": "Penthouse in Tokyo",
        "price": "$5,000,000",
        "description": "A luxurious 4-bedroom penthouse with panoramic views of the Tokyo skyline, offering exclusive living with unmatched amenities.",
        "address": "Tokyo, Japan",
        "bedrooms": 4,
        "bathrooms": 3,
        "squareFeet": "3500",
        "yearBuilt": "2020",
        "propertyType": "Penthouse",
        "country": "Japan",
        "city": "Tokyo",
        "priceRange": "2,000,000+",
        "squareFeetRange": "3000 - 5000 sq ft",
        "yearBuiltRange": "2021+",
        "parking": "Available",
        "garden": "No",
        "flooring": "Tile",
        "view": "City",
        "airConditioning": "Available",
        "heating": "Central",
        "pool": "Not Available",
        "balcony": "Available",
        "roof": "Flat",
        "security": "Available",
        "schools": "Yes",
        "internet": "Available",
        "gym": "Available",
        "storage": "Available",
        "shopping": "Close",
        "hospital": "Yes",
        "park": "No"
    },
    {
        "imgUrl": "https://via.placeholder.com/250",
        "title": "Oceanfront Villa in Sydney",
        "price": "$7,000,000",
        "description": "A breathtaking 5-bedroom villa overlooking Bondi Beach, with state-of-the-art amenities and luxury finishes.",
        "address": "Sydney, Australia",
        "bedrooms": 5,
        "bathrooms": 4,
        "squareFeet": "6000",
        "yearBuilt": "2021",
        "propertyType": "Villa",
        "country": "Australia",
        "city": "Sydney",
        "priceRange": "2,000,000+",
        "squareFeetRange": "5000+ sq ft",
        "yearBuiltRange": "2021+",
        "parking": "Available",
        "garden": "Yes",
        "flooring": "Marble",
        "view": "Sea",
        "airConditioning": "Available",
        "heating": "Central",
        "pool": "Available",
        "balcony": "Available",
        "roof": "Flat",
        "security": "Available",
        "schools": "Yes",
        "internet": "Available",
        "gym": "Available",
        "storage": "Available",
        "shopping": "Close",
        "hospital": "Yes",
        "park": "Yes"
    },
    {
        "imgUrl": "https://via.placeholder.com/250",
        "title": "Riverside House in Geneva",
        "price": "$3,800,000",
        "description": "A luxurious 6-bedroom house situated on the banks of Lake Geneva, offering tranquility, spacious interiors, and modern amenities.",
        "address": "Geneva, Switzerland",
        "bedrooms": 6,
        "bathrooms": 5,
        "squareFeet": "7000",
        "yearBuilt": "2019",
        "propertyType": "House",
        "country": "Switzerland",
        "city": "Geneva",
        "priceRange": "2,000,000+",
        "squareFeetRange": "5000+ sq ft",
        "yearBuiltRange": "2011 - 2020",
        "parking": "Available",
        "garden": "Yes",
        "flooring": "Wood",
        "view": "Lake",
        "airConditioning": "Available",
        "heating": "Central",
        "pool": "Not Available",
        "balcony": "Available",
        "roof": "Sloped",
        "security": "Available",
        "schools": "Yes",
        "internet": "Available",
        "gym": "Available",
        "storage": "Available",
        "shopping": "Close",
        "hospital": "Yes",
        "park": "Yes"
    },
    {
        "imgUrl": "https://via.placeholder.com/250",
        "title": "Mountain Chalet in Zurich",
        "price": "$2,200,000",
        "description": "A cozy 4-bedroom chalet nestled in the Swiss Alps, offering privacy, breathtaking mountain views, and a luxurious wood interior.",
        "address": "Zurich, Switzerland",
        "bedrooms": 4,
        "bathrooms": 3,
        "squareFeet": "3500",
        "yearBuilt": "2018",
        "propertyType": "Chalet",
        "country": "Switzerland",
        "city": "Zurich",
        "priceRange": "1,000,000 - 2,000,000",
        "squareFeetRange": "3000 - 5000 sq ft",
        "yearBuiltRange": "2011 - 2020",
        "parking": "Available",
        "garden": "Yes",
        "flooring": "Wood",
        "view": "Mountain",
        "airConditioning": "Not Available",
        "heating": "Individual",
        "pool": "Not Available",
        "balcony": "Available",
        "roof": "Sloped",
        "security": "Not Available",
        "schools": "Yes",
        "internet": "Available",
        "gym": "Not Available",
        "storage": "Not Available",
        "shopping": "Far",
        "hospital": "Yes",
        "park": "Yes"
    },
    {
        "imgUrl": "https://via.placeholder.com/250",
        "title": "Villa in Cape Town",
        "price": "$3,200,000",
        "description": "A stunning 5-bedroom villa offering panoramic views of Table Mountain and the Atlantic Ocean, with expansive outdoor living areas.",
        "address": "Cape Town, South Africa",
        "bedrooms": 5,
        "bathrooms": 4,
        "squareFeet": "6000",
        "yearBuilt": "2020",
        "propertyType": "Villa",
        "country": "South Africa",
        "city": "Cape Town",
        "priceRange": "2,000,000+",
        "squareFeetRange": "5000+ sq ft",
        "yearBuiltRange": "2021+",
        "parking": "Available",
        "garden": "Yes",
        "flooring": "Wood",
        "view": "Mountain",
        "airConditioning": "Available",
        "heating": "Central",
        "pool": "Available",
        "balcony": "Available",
        "roof": "Flat",
        "security": "Available",
        "schools": "Yes",
        "internet": "Available",
        "gym": "Available",
        "storage": "Available",
        "shopping": "Close",
        "hospital": "Yes",
        "park": "Yes"
    },
    {
        "imgUrl": "https://via.placeholder.com/250",
        "title": "Luxury Estate in Madrid",
        "price": "$6,000,000",
        "description": "A grand 7-bedroom estate in the outskirts of Madrid, with vast gardens, a private pool, and luxurious finishing throughout.",
        "address": "Madrid, Spain",
        "bedrooms": 7,
        "bathrooms": 6,
        "squareFeet": "10000",
        "yearBuilt": "2021",
        "propertyType": "Estate",
        "country": "Spain",
        "city": "Madrid",
        "priceRange": "2,000,000+",
        "squareFeetRange": "5000+ sq ft",
        "yearBuiltRange": "2021+",
        "parking": "Available",
        "garden": "Yes",
        "flooring": "Marble",
        "view": "Park",
        "airConditioning": "Available",
        "heating": "Central",
        "pool": "Available",
        "balcony": "Available",
        "roof": "Flat",
        "security": "Available",
        "schools": "Yes",
        "internet": "Available",
        "gym": "Available",
        "storage": "Available",
        "shopping": "Close",
        "hospital": "Yes",
        "park": "Yes"
    }
]
